#!/bin/sh

case "$1" in
    start)
        echo "Start aesdchar"
        /usr/bin/aesdchar_load
        ;;
    stop)
        echo "Stop aesdchar"
        /usr/bin/aesdchar_unload
        ;;
    *)
        echo "Usage: $0 {start|stop}"
    exit 1
esac

exit 0