#!/bin/sh

case "$1" in
    start)
        echo "Start faulty"
        /usr/bin/module_load faulty
        ;;
    stop)
        echo "Stop faulty"
        /usr/bin/module_unload faulty
        ;;
    *)
        echo "Usage: $0 {start|stop}"
    exit 1
esac

exit 0