#!/bin/sh

case "$1" in
    start)
        echo "Start hello & faulty"
        /usr/bin/module_load hello
        /usr/bin/module_load faulty
        ;;
    stop)
        echo "Stop hello & faulty"
        /usr/bin/module_unload hello
        /usr/bin/module_unload faulty
        ;;
    *)
        echo "Usage: $0 {start|stop}"
    exit 1
esac

exit 0